# Generated by Django 4.2.1 on 2023-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('gene_id', models.CharField(max_length=255)),
                ('sequence', models.TextField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
